---
  - name: check nodejs is installed
    command: /usr/bin/node -v
    register: node_installed
    ignore_errors: true
    changed_when: False
  
  - name: download nodejs
    get_url:
      url: https://rpm.nodesource.com/setup_8.x
      dest: /tmp/node_setup.sh
      mode: 0755
    when: node_installed is failed
  
  - name: execute nodejs setup script
    shell: /tmp/node_setup.sh
    when: node_installed is failed
    become: yes
  
  - name: node install
    yum:
      name: "nodejs"
      state: latest
    become: yes
  
  - name: add yarn repository
    get_url:
      url: https://dl.yarnpkg.com/rpm/yarn.repo
      dest: /etc/yum.repos.d/yarn.repo
    become: yes
  
  - name: yum install
    yum:
      name: "yarn"
      state: latest
    become: yes